# Generated by Django 2.2.6 on 2019-10-29 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191024_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True)),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
                ('info', models.CharField(max_length=512, null=True)),
                ('address', models.CharField(max_length=512, null=True)),
                ('star_rating', models.PositiveIntegerField(blank=True, default=0)),
                ('num_ratings', models.PositiveIntegerField(blank=True, default=0)),
                ('fenced_in', models.BooleanField(default=False)),
                ('off_leash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateField()),
                ('duration', models.DurationField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dog')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Park')),
            ],
        ),
        migrations.CreateModel(
            name='ParkReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=512, null=True)),
                ('star_rating', models.PositiveIntegerField(blank=True, default=0)),
                ('timeposted', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.AddField(
            model_name='park',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='app.ParkReview'),
        ),
    ]
