# Generated by Django 2.2.7 on 2019-11-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(default='Un-named', max_length=150),
        ),
        migrations.AlterField(
            model_name='park',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parkreview',
            name='review',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
