# Generated by Django 2.2.6 on 2019-10-24 23:34

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Un-named', max_length=140)),
                ('dog_pfp', models.FileField(blank=True, null=True, upload_to=app.models.get_image_path)),
                ('breed', models.CharField(max_length=140, null=True)),
                ('dog_size', models.CharField(max_length=140, null=True)),
                ('temperament', models.PositiveIntegerField(blank=True, default=5)),
                ('activity_level', models.PositiveIntegerField(blank=True, default=5)),
                ('volume', models.PositiveIntegerField(blank=True, default=5)),
                ('notes', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dogs',
            field=models.ManyToManyField(to='app.Dog'),
        ),
    ]
