# Generated by Django 2.2.7 on 2019-12-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favoritePark',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
