# Generated by Django 2.2.6 on 2019-11-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='park',
            name='lon',
            field=models.FloatField(),
        ),
    ]
