# Generated by Django 2.2.7 on 2019-11-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
